version: '3.1'

services:
  jupyterlab:
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - jupyternet
    volumes:
      - "./jupyterlab/notebook:/anaconda"
    env_file: .env
#      command: "jupyter lab --ip=0.0.0.0 --no-browser --port=8888 --notebook-dir=/home/jupyter/notebook --NotebookApp.password=${ACCESS_TOKEN}"
    command: "jupyter lab --NotebookApp.password=${ACCESS_TOKEN}"


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 9998:80
    networks:
      - jupyternet
    depends_on:
      - jupyterlab
networks:
  jupyternet:

